// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Winecellar.Infrastructure.Context;

#nullable disable

namespace Winecellar.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Winecellar.Domain.Models.Wine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("UUID")
                        .HasColumnName("id")
                        .HasColumnOrder(1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(36)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("wines");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f5b3313d-5336-4663-82a3-dd2287ab6930"),
                            Name = "Wine 1"
                        },
                        new
                        {
                            Id = new Guid("9ac1e64a-417f-4a3e-ab83-82478d2331e7"),
                            Name = "Wine 2"
                        },
                        new
                        {
                            Id = new Guid("9bc1e64a-417f-4a3e-ab83-82478d2331e8"),
                            Name = "Wine 2"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
